/**
 * LUMIÈRE & CO. - Accessories Data & Translations
 * Product Catalog, Categories, Currencies, and Reviews
 */

const CURRENCIES = {
  EGP: { symbol: 'ج.م', rate: 1, name: 'جنيه مصري' },
  SAR: { symbol: 'ر.س', rate: 0.076, name: 'ريال سعودي' },
  USD: { symbol: '$', rate: 0.020, name: 'دولار أمريكي' }
};

const CATEGORIES = [
  { id: 'all', name_ar: 'الكل', name_en: 'All Items', icon: 'fa-gem' },
  { id: 'women', name_ar: 'إكسسوارات نسائية', name_en: "Women's Collection", icon: 'fa-venus' },
  { id: 'men', name_ar: 'إكسسوارات رجالية', name_en: "Men's Collection", icon: 'fa-mars' },
  { id: 'necklaces', name_ar: 'قلائد وسلاسل', name_en: 'Necklaces & Pendants', icon: 'fa-ring' },
  { id: 'rings', name_ar: 'خواتم ومحابس', name_en: 'Rings & Bands', icon: 'fa-circle-notch' },
  { id: 'watches', name_ar: 'ساعات فاخرة', name_en: 'Luxury Watches', icon: 'fa-clock' },
  { id: 'bracelets', name_ar: 'أساور ومعاطم', name_en: 'Bracelets', icon: 'fa-link' }
];

const PRODUCTS = [
  {
    id: 'prod-001',
    name_ar: 'قلادة الزمرد الملكي ذهب 18K',
    name_en: 'Royal Emerald Pendant (18K Gold)',
    category: 'necklaces',
    gender: 'women',
    price_egp: 4850,
    original_price_egp: 5500,
    image: 'assets/images/gold_necklace.png',
    rating: 4.9,
    reviews_count: 38,
    is_bestseller: true,
    is_new: true,
    material: '18k_gold',
    material_ar: 'ذهب عيار 18 وحجر زمرد نقي',
    material_en: '18K Yellow Gold & Pure Teardrop Emerald',
    description_ar: 'قلادة فاخرة مصممة يدويًا بحرفية عالية من الذهب الخالص عيار 18K وتتوسطها حبة زمرد طبيعي مقطوعة بحرفية دقيقة لتعكس الأناقة والجاذبية في كل مناسبة.',
    description_en: 'A handcrafted masterpiece of pure 18K gold featuring a mesmerizing teardrop natural emerald, reflecting timeless sophistication and royalty.',
    sizes: ['40 cm', '45 cm', '50 cm'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-002',
    name_ar: 'طقم خواتم الماس والذهب المرصعة',
    name_en: 'Imperial Diamond Stacked Rings',
    category: 'rings',
    gender: 'women',
    price_egp: 3900,
    original_price_egp: 4400,
    image: 'assets/images/diamond_rings.png',
    rating: 5.0,
    reviews_count: 52,
    is_bestseller: true,
    is_new: false,
    material: 'diamond',
    material_ar: 'ذهب أبيض وأصفر عيار 18 مع ماس طبيعي',
    material_en: '18K White & Yellow Gold with Natural Diamonds',
    description_ar: 'تجميعة متناسقة من الخواتم المرصعة بفصوص الألماس البراقة ذات التصميم المموج الفريد، تمنحك إمكانية ارتدائها منفردة أو متداخلة لمظهر ساحر.',
    description_en: 'A harmoniously designed stack of diamond-encrusted 18K gold bands that can be worn individually or layered for an unforgettable glow.',
    sizes: ['5 US', '6 US', '7 US', '8 US'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-003',
    name_ar: 'ساعة كرونوغراف ذهب ملكي سويسري',
    name_en: 'Royal Sovereign Chronograph Watch',
    category: 'watches',
    gender: 'unisex',
    price_egp: 8900,
    original_price_egp: 9800,
    image: 'assets/images/luxury_watch.png',
    rating: 4.8,
    reviews_count: 24,
    is_bestseller: true,
    is_new: true,
    material: '18k_gold',
    material_ar: 'ستانلس ستيل مطلي بالذهب ومقاوم للمياه 50m',
    material_en: 'Gold Plated Stainless Steel & Sapphire Crystal Glass',
    description_ar: 'ساعة يد فاخرة بمكينة سويسرية دقيقة، وميناء من بلور الزفير المقاوم للخدش، مع سوار مطلي بالذهب الخالص يدوم طويلاً.',
    description_en: 'Swiss-movement luxury timepiece encased in scratch-resistant sapphire crystal and finished with polished 18K gold links.',
    sizes: ['38mm', '42mm'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-004',
    name_ar: 'إسوارة اللؤلؤ الطبيعي وسلسلة الذهب',
    name_en: 'Freshwater Pearl & Gold Chain Bracelet',
    category: 'bracelets',
    gender: 'women',
    price_egp: 2750,
    original_price_egp: 3100,
    image: 'assets/images/pearl_bracelet.png',
    rating: 4.7,
    reviews_count: 41,
    is_bestseller: false,
    is_new: true,
    material: 'rose_gold',
    material_ar: 'لؤلؤ مياه عذبة طبيعي وذهب روز جولد 18K',
    material_en: 'Natural Freshwater Pearls & 18K Rose Gold Chain',
    description_ar: 'إسوارة رقيقة تجمع بين دلال اللؤلؤ الطبيعي وبريق سلسلة الذهب الوردي الناعمة، مع قفل قابل للتعديل لتناسب كافة المعاصم.',
    description_en: 'Delicate luxury bracelet combining lustrous natural freshwater pearls with a luminous 18K rose gold adjustable chain.',
    sizes: ['16 cm', '18 cm', '20 cm'],
    engraving_available: false,
    in_stock: true
  },
  {
    id: 'prod-005',
    name_ar: 'سوار الجلد الإيطالي الفاخر وتيتانيوم الذهب (رجالي)',
    name_en: 'Gentleman Braided Italian Leather Bracelet',
    category: 'bracelets',
    gender: 'men',
    price_egp: 1950,
    original_price_egp: 2300,
    image: 'assets/images/mens_bracelet.png',
    rating: 4.9,
    reviews_count: 67,
    is_bestseller: true,
    is_new: true,
    material: 'leather',
    material_ar: 'جلد طبيعي إيطالي وقفل ستانلس وتيتانيوم ذهبي',
    material_en: 'Braided Italian Leather & Brushed Gold Stainless Clasp',
    description_ar: 'سوار رجالي فاخر من الجلد الطبيعي المجدول يدوياً بزخرفة ذهبية غير لامعة، يمنح إطلالتك الرجالية طابعاً هادئاً وفخماً في آن واحد.',
    description_en: 'Premium men’s braided natural Italian leather bracelet styled with a brushed gold magnetic titanium closure for effortless masculine elegance.',
    sizes: ['19 cm', '21 cm', '23 cm'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-006',
    name_ar: 'خاتم الأونيكس الأسود والفولاذ الذهبي (رجالي)',
    name_en: 'Black Onyx & Gold Signet Ring (Men)',
    category: 'rings',
    gender: 'men',
    price_egp: 2200,
    original_price_egp: 2600,
    image: 'assets/images/diamond_rings.png',
    rating: 4.8,
    reviews_count: 19,
    is_bestseller: false,
    is_new: false,
    material: 'sterling_silver',
    material_ar: 'حجر أونيكس أسود طبيعي وستانلس مطلي بالذهب 18K',
    material_en: 'Natural Black Onyx Stone & 18K Gold Plated Steel',
    description_ar: 'خاتم رجالي ملكي كلاسيكي بحجر الأونيكس الأسود الداكن والحدود الذهبية المحفورة، لمظهر يوحي بالقوة والأصالة.',
    description_en: 'A bold, regal signet ring for men featuring a deep obsidian black onyx inlay framed by polished gold accents.',
    sizes: ['8 US', '9 US', '10 US', '11 US', '12 US'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-007',
    name_ar: 'سلسلة العقيق الناري والذهب عيار 18',
    name_en: 'Celestial Amber Gold Necklace',
    category: 'necklaces',
    gender: 'women',
    price_egp: 3600,
    original_price_egp: 4100,
    image: 'assets/images/gold_necklace.png',
    rating: 4.9,
    reviews_count: 29,
    is_bestseller: false,
    is_new: true,
    material: '18k_gold',
    material_ar: 'ذهب عيار 18 وحجر عقيق دافئ',
    material_en: '18K Solid Yellow Gold & Natural Amber Stone',
    description_ar: 'سلسلة ذهبية أنيقة بتصميم عصري ملهم يحاكي الدفء والأشعة الذهبية، تناسب الإطلالات اليومية الفخمة.',
    description_en: 'A modern gold chain with an amber gemstone pendant designed to catch the warm sunlight in subtle beauty.',
    sizes: ['45 cm', '50 cm'],
    engraving_available: true,
    in_stock: true
  },
  {
    id: 'prod-008',
    name_ar: 'ساعة الفولاذ الفضي والأسود المليكية (رجالي)',
    name_en: 'Executive Obsidian Chrono (Men)',
    category: 'watches',
    gender: 'men',
    price_egp: 6400,
    original_price_egp: 7200,
    image: 'assets/images/luxury_watch.png',
    rating: 5.0,
    reviews_count: 31,
    is_bestseller: true,
    is_new: false,
    material: 'sterling_silver',
    material_ar: 'ستانلس ستيل فضي غير قابل للصدأ وميناء أسود',
    material_en: 'Polished Stainless Steel & Deep Obsidian Dial',
    description_ar: 'ساعة رجالية مميزة بتفاصيل هندسية صارمة وتصميم يجمع بين الصلابة والرقي لتناسب اجتماعات العمل والمناسبات الرسمية.',
    description_en: 'An executive watch built with precision craftsmanship, high contrast dial, and comfortable steel link mesh.',
    sizes: ['42mm'],
    engraving_available: true,
    in_stock: true
  }
];

const REVIEWS = [
  {
    id: 1,
    author_ar: 'سارة الأحمد',
    author_en: 'Sarah Al-Ahmad',
    rating: 5,
    date: 'منذ يومين',
    comment_ar: 'التغليف أفخم مما كنت متوقعة! قلادة الزمرد جودتها ممتازة والذهب بيلمع بطريقة ساحرة. وصلني خلال 24 ساعة فقط.',
    comment_en: 'The packaging exceeded my expectations! The emerald necklace is top tier quality and shines beautifully. Delivered in 24 hrs!',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 2,
    author_ar: 'مهندس أحمد السعيد',
    author_en: 'Eng. Ahmed El-Sayed',
    rating: 5,
    date: 'منذ 4 أيام',
    comment_ar: 'اشتريت سوار الجلد الرجالي وساعة الكرونوغراف. الجودة تضاهي الماركات العالمية العالمية والتعامل محترم جداً.',
    comment_en: 'Bought the men braided leather bracelet and Chrono watch. Quality matches high-end international brands. Highly recommended.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 3,
    author_ar: 'نور الهدى محمود',
    author_en: 'Nour El-Hoda',
    rating: 5,
    date: 'منذ أسبوع',
    comment_ar: 'طقم الخواتم الذهب والماس رائع جداً، استخدمت أداة التنسيق بالموقع وكانت النتيجة حقيقية ومطابقة تماماً.',
    comment_en: 'The stacked gold diamond ring set is drop-dead gorgeous. Used the stack builder on site and product came identical to preview!',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200'
  }
];

const UI_TRANSLATIONS = {
  ar: {
    brand_name: 'NEXOR',
    brand_tagline: 'إكسسوارات ومجوهرات فاخرة',
    announcement: '✨ شحن مجاني لجميع الطلبات الفاخرة + كارت إهداء ملكي مخصص مجاناً من NEXOR! ✨',
    nav_home: 'الرئيسية',
    nav_catalog: 'المنتجات',
    nav_women: 'حريمي',
    nav_men: 'رجالي',
    nav_builder: 'صمم طقمك',
    nav_story: 'قصتنا',
    nav_reviews: 'آراء العملاء',
    search_placeholder: 'ابحث في تشكيلة NEXOR...',
    cart_title: 'حقيبة التسوق',
    cart_empty: 'حقيبة التسوق فارغة حالياً',
    free_shipping_calc: 'أضيفي {amount} للشحن المجاني!',
    free_shipping_unlocked: '🎉 مبروك! حصلتِ على شحن مجاني من NEXOR!',
    subtotal: 'المجموع الفرعي:',
    shipping: 'الشحن:',
    free: 'مجاني',
    discount: 'الخصم:',
    total: 'الإجمالي النهائي:',
    checkout_btn: 'إتمام الطلب الآن',
    add_to_cart: 'إضافة للسلة',
    quick_view: 'معاينة سريعة',
    bestseller: 'الأكثر مبيعاً',
    new_arrival: 'جديد',
    out_of_stock: 'نفد من المخزون',
    material_label: 'الخامة:',
    engraving_label: 'إضافة حفر اسم مخصص (مجاناً):',
    engraving_placeholder: 'اكتبي الاسم أو التاريخ المطلوب...',
    size_label: 'المقاس المطلوب:',
    filter_all: 'الجميع',
    filter_gender: 'النوع:',
    filter_all_genders: 'كل الفئات',
    filter_women: 'نسائي',
    filter_men: 'رجالي',
    filter_material: 'الخامة:',
    filter_all_materials: 'جميع الخامات',
    sort_by: 'الترتيب حسب:',
    sort_featured: 'المميز',
    sort_price_low: 'السعر: من الأقل للأعلى',
    sort_price_high: 'السعر: من الأعلى للأقل',
    sort_rating: 'الأعلى تقييماً',
    builder_title: 'أداة تنسيق الأطقم والستايل (Mix & Match)',
    builder_subtitle: 'اختاري قطعك المفضلة لبناء طقم مجوهرات مخصص لك وحصلي على خصم 15% فوري!',
    select_necklace: 'اختر القلادة',
    select_ring: 'اختر الخاتم',
    select_bracelet: 'اختر السوار',
    builder_total: 'سعر الطقم المنسق:',
    builder_add_all: 'إضافة الطقم كاملاً للسلة (مع خصم 15%)',
    size_guide_btn: '📐 حاسبة ودليل المقاسات',
    checkout_title: 'إتمام الطلب الشريف',
    customer_info: 'بيانات العميل والشحن',
    full_name: 'الاسم بالكامل',
    phone: 'رقم الهاتف / الواتساب',
    address: 'عنوان التوصيل بالتفصيل (المحافظة / المدينة / الشارع)',
    payment_method: 'طريقة الدفع الفاخرة',
    cod: 'الدفع عند الاستلام (COD)',
    vodafone: 'فودافون كاش / اتصالات كاش',
    instapay: 'إنستا باي InstaPay',
    card: 'بطاقات ائتمان (Mastercard / Visa)',
    confirm_order: 'تأكيد وإرسال الطلب',
    hero_title: 'عالم NEXOR للفخامة والأناقة',
    hero_desc: 'تشكيلة ساحرة من الإكسسوارات والمجوهرات النسائية والرجالية المصممة يدويًا بأرقى معايير الحرفية العالمية.',
    hero_cta: 'تصفح التشكيلة الجديدة',
    hero_secondary_cta: 'صمم طقمك الخاص',
    craft_title: 'سر الحرفية والضمان الملكي من NEXOR',
    craft_1_title: 'ذهب 18K ومعادن فاخرة',
    craft_1_desc: 'نستخدم الذهب النقي، الفضة الإسترليني 925، والأونيكس الطبيعي المقاوم للتغير.',
    craft_2_title: 'تغليف NEXOR الفاخر',
    craft_2_desc: 'تصلك كل قطعة في علبة مخملية سوداء بختم NEXOR الذهبي مع كارت إهداء ملكي.',
    craft_3_title: 'ضمان الذهبي سنتين',
    craft_3_desc: 'نضمن لك استبدال أو صيانة القطعة مجاناً خلال سنتين من تاريخ الشراء.',
    copyright: 'جميع الحقوق محفوظة © 2026 NEXOR. الفخامة والتميز.'
  },
  en: {
    brand_name: 'NEXOR',
    brand_tagline: 'Luxury Accessories & Jewelry',
    announcement: '✨ Free Shipping on NEXOR luxury orders over $100 + Signature Gift Note! ✨',
    nav_home: 'Home',
    nav_catalog: 'Products',
    nav_women: 'Women',
    nav_men: 'Men',
    nav_builder: 'Stack Builder',
    nav_story: 'Our Story',
    nav_reviews: 'Reviews',
    search_placeholder: 'Search NEXOR fine collection...',
    cart_title: 'Shopping Bag',
    cart_empty: 'Your shopping bag is currently empty',
    free_shipping_calc: 'Add {amount} for Free Express Shipping!',
    free_shipping_unlocked: '🎉 Congrats! You unlocked Free Shipping!',
    subtotal: 'Subtotal:',
    shipping: 'Shipping:',
    free: 'FREE',
    discount: 'Discount:',
    total: 'Final Total:',
    checkout_btn: 'Proceed to Checkout',
    add_to_cart: 'Add to Bag',
    quick_view: 'Quick View',
    bestseller: 'Bestseller',
    new_arrival: 'New',
    out_of_stock: 'Out of Stock',
    material_label: 'Material:',
    engraving_label: 'Custom Name Engraving (Free):',
    engraving_placeholder: 'Enter name or date to engrave...',
    size_label: 'Select Size:',
    filter_all: 'All',
    filter_gender: 'Gender:',
    filter_all_genders: 'All Collections',
    filter_women: "Women's",
    filter_men: "Men's",
    filter_material: 'Material:',
    filter_all_materials: 'All Materials',
    sort_by: 'Sort By:',
    sort_featured: 'Featured',
    sort_price_low: 'Price: Low to High',
    sort_price_high: 'Price: High to Low',
    sort_rating: 'Top Rated',
    builder_title: 'Mix & Match Stack Builder',
    builder_subtitle: 'Combine your favorite pieces to craft a personalized NEXOR set and save 15% automatically!',
    select_necklace: 'Choose Necklace',
    select_ring: 'Choose Ring',
    select_bracelet: 'Choose Bracelet',
    builder_total: 'Custom Set Price:',
    builder_add_all: 'Add Full Set to Bag (Save 15%)',
    size_guide_btn: '📐 Interactive Size Calculator',
    checkout_title: 'Complete Your Order',
    customer_info: 'Shipping & Customer Info',
    full_name: 'Full Name',
    phone: 'Phone Number / WhatsApp',
    address: 'Full Shipping Address (City, Street, Building)',
    payment_method: 'Payment Option',
    cod: 'Cash on Delivery (COD)',
    vodafone: 'Vodafone Cash / Mobile Wallet',
    instapay: 'InstaPay Direct Transfer',
    card: 'Credit / Debit Card',
    confirm_order: 'Place Order Now',
    hero_title: 'NEXOR World of Elegance',
    hero_desc: 'Handcrafted luxury jewelry and executive accessories for women and men, created with uncompromised artistry.',
    hero_cta: 'Explore New Arrivals',
    hero_secondary_cta: 'Customize Your Stack',
    craft_title: 'NEXOR Craftsmanship & Royal Guarantee',
    craft_1_title: '18K Gold & Fine Metals',
    craft_1_desc: 'We craft using solid 18K gold, 925 sterling silver, and natural certified gemstones.',
    craft_2_title: 'NEXOR Signature Velvet Box',
    craft_2_desc: 'Every piece arrives wrapped in a plush black velvet presentation box with wax-sealed gift note.',
    craft_3_title: '2-Year Gold Warranty',
    craft_3_desc: 'Enjoy peace of mind with complimentary replacement or polish for two full years.',
    copyright: 'All Rights Reserved © 2026 NEXOR. Timeless Luxury.'
  }
};
